[package]
name = "mateus-image"
version = "1.4.0"
edition = "2021"
description = "simple CLI program to make colors of image to be Matissoss' colorscheme"
license = "MIT"

[dependencies]
image = "0.25.5"
